name: Flask Build
on:
  push:
    branches:
      - "main"
jobs: 
  build_and_push:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: set_outputs
        run: echo "commit_sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: docker_login
        uses: docker/login-action@v2
        with:
          registry: us-west3-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.DEVOPS_SERVICE_ACCOUNT }}
      - name: docker_build
        id: docker_build
        env: 
          FLASK_IMAGE: us-west3-docker.pkg.dev/${{ secrets.GOOGLE_ID }}/devops-training/cfish/flask:${{ env.commit_sha }}
        run: docker build -t $FLASK_IMAGE .
      - name: docker_push
        run: docker push us-west3-docker.pkg.dev/${{ secrets.GOOGLE_ID }}/devops-training/cfish/flask:${{ env.commit_sha }}
